import { openDB } from 'idb';
import type { DBSchema, IDBPDatabase } from 'idb';

export interface SyncOperation {
  id: string; // UUID generated by client
  type: 'CREATE_TRIAGE' | 'CREATE_MEDICAL_RECORD' | 'UPDATE_APPOINTMENT_STATUS' | 'CREATE_REFERRAL' | 'UPDATE_TELECONSULTATION_STATUS';
  payload: any;
  timestamp: string;
  status: 'PENDING' | 'SYNCING' | 'FAILED' | 'CONFLICT';
  error?: string;
}

interface SIHHealthcareDB extends DBSchema {
  sync_queue: {
    key: string;
    value: SyncOperation;
    indexes: { 'by-status': string };
  };
}

let dbPromise: Promise<IDBPDatabase<SIHHealthcareDB>> | null = null;

export const getDB = () => {
  if (!dbPromise) {
    dbPromise = openDB<SIHHealthcareDB>('sih-healthcare-db', 1, {
      upgrade(db) {
        if (!db.objectStoreNames.contains('sync_queue')) {
          const store = db.createObjectStore('sync_queue', { keyPath: 'id' });
          store.createIndex('by-status', 'status');
        }
      },
    });
  }
  return dbPromise;
};

export const addSyncOperation = async (op: Omit<SyncOperation, 'status'>) => {
  const db = await getDB();
  await db.put('sync_queue', {
    ...op,
    status: 'PENDING',
  });
};

export const getPendingOperations = async () => {
  const db = await getDB();
  return db.getAllFromIndex('sync_queue', 'by-status', 'PENDING');
};

export const updateOperationStatus = async (id: string, status: SyncOperation['status'], error?: string) => {
  const db = await getDB();
  const tx = db.transaction('sync_queue', 'readwrite');
  const store = tx.objectStore('sync_queue');
  const op = await store.get(id);
  if (op) {
    op.status = status;
    op.error = error;
    await store.put(op);
  }
  await tx.done;
};

export const removeOperation = async (id: string) => {
  const db = await getDB();
  await db.delete('sync_queue', id);
};

export const clearSyncQueue = async () => {
  const db = await getDB();
  await db.clear('sync_queue');
};
