import { Request, Response } from 'express';
import { z } from 'zod';
import { db } from './db';
import crypto from 'crypto';
import { AuthRequest } from './auth.middleware';
import { evaluateTriage } from './triage.rules';

const DISCLAIMER = "DISCLAIMER: This assessment is generated by a rule-based algorithm and is NOT a medical diagnosis. Final clinical decisions and diagnoses must be made by qualified healthcare professionals.";

const triageSchema = z.object({
  patientId: z.string().uuid(),
  vitals: z.object({
    temperature: z.number().optional(),
    heartRate: z.number().min(0).max(300).optional(),
    respiratoryRate: z.number().min(0).max(100).optional(),
    spO2: z.number().min(0).max(100).optional(),
    systolicBp: z.number().min(0).max(300).optional(),
    diastolicBp: z.number().min(0).max(200).optional(),
  }).optional(),
  symptoms: z.array(z.string()).default([]),
  riskFactors: z.array(z.string()).default([])
});

export const createAssessment = (req: AuthRequest, res: Response): void => {
  try {
    const parsed = triageSchema.parse(req.body);
    const userId = req.user!.id;

    // Verify patient exists
    const patientExists = db.prepare('SELECT 1 FROM patients WHERE id = ?').get(parsed.patientId);
    if (!patientExists) {
      res.status(404).json({ error: 'Patient not found' });
      return;
    }

    // Run CDSS rule engine
    const triageResult = evaluateTriage({
      vitals: parsed.vitals,
      symptoms: parsed.symptoms,
      riskFactors: parsed.riskFactors
    });

    const id = crypto.randomUUID();

    db.prepare(`
      INSERT INTO triage_assessments 
      (id, patientId, assessedBy, vitals, symptoms, riskFactors, urgencyLevel, recommendedAction, referralNeeded, disclaimer) 
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      id, parsed.patientId, userId, 
      parsed.vitals ? JSON.stringify(parsed.vitals) : null,
      JSON.stringify(parsed.symptoms),
      JSON.stringify(parsed.riskFactors),
      triageResult.urgencyLevel,
      triageResult.recommendedAction,
      triageResult.referralNeeded ? 1 : 0,
      DISCLAIMER
    );

    res.status(201).json({
      message: 'Assessment completed successfully',
      assessmentId: id,
      result: triageResult,
      disclaimer: DISCLAIMER
    });

  } catch (err: any) {
    if (err instanceof z.ZodError) {
      res.status(400).json({ error: 'Invalid input data', details: err.errors });
    } else {
      res.status(500).json({ error: 'Internal server error' });
    }
  }
};

export const getPatientAssessments = (req: AuthRequest, res: Response): void => {
  try {
    const patientId = req.params.patientId;
    const assessments = db.prepare(`
      SELECT t.*, u.username as assessedByName
      FROM triage_assessments t
      JOIN users u ON t.assessedBy = u.id
      WHERE t.patientId = ?
      ORDER BY t.createdAt DESC
    `).all(patientId);
    
    // parse JSON fields
    const formatted = assessments.map((a: any) => ({
      ...a,
      vitals: a.vitals ? JSON.parse(a.vitals) : null,
      symptoms: a.symptoms ? JSON.parse(a.symptoms) : [],
      riskFactors: a.riskFactors ? JSON.parse(a.riskFactors) : [],
      referralNeeded: !!a.referralNeeded
    }));

    res.json({ assessments: formatted });
  } catch (err) {
    res.status(500).json({ error: 'Internal server error' });
  }
};
